FROM python:3.6.5-alpine3.7

RUN apk add --update make git 
RUN pip install pipenv twine
RUN mkdir /opt

RUN python --version && pip --version && pipenv --version && make --version && git --version && twine --version
