FROM python:3.7-alpine3.9

RUN apk add --update make git
RUN pip install pipenv twine
RUN mkdir -p /opt

RUN python --version && pip --version && pipenv --version && make --version && git --version && twine --version
